version: '3'
services:
  cartao_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: Eraumavez
      POSTGRES_USER: desafio
      POSTGRES_DB: Ad&d
    ports:
      - '5433:5432'

volumes:
  db-data:
    driver: local
