INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Guerrero', 'Hero', 20, 7, 5, 6, 1, 12);
INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Bárbaro','Hero', 21, 10, 2, 5, 2, 8);
INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Cavaleiro','Hero', 26, 6, 8, 3, 2, 6);
INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Gigante', 'Monster', 34, 10, 4, 4, 2, 6);
INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Lobisomen', 'Monster', 34, 7, 4, 7, 2, 4);
INSERT INTO CHARACTER (name, TYPE, HEALTH_POINTS, STRENGTH, DEFENCE, AGILITY, DAMAGE_DICE, DICE_TYPE) VALUES ('Orc', 'Monster', 42, 7, 1, 2, 3, 4);
